language: php
php:
- 5.6
- 7.0
install:
- composer install
script:
- ./vendor/bin/phing test
after_success:
- if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then ./vendor/bin/coveralls -vvv; fi
notifications:
  email:
    recipients:
    - nils.destoop@wunderkraut.com
    - wouter.vanelslander@wunderkraut.com