# Cross-origin resource sharing related settings.
cors:
  # Allowed origins. Add one entry for each domain allowed to access the application.
  # Always include the protocol (http or https) and if not default for the
  # protocol, also the port number!
  origins:
    - http://localhost:9000/
    - http://localhost:9000

# UiTID related settings.
uitid:
  consumer:
    key:
    secret:
  base_url: https://acc2.uitid.be/uitid/rest/

# debug settings
debug: false
