# Cross-origin resource sharing related settings.
cors:
  # Allowed origins. Add one entry for each domain allowed to access the application.
  # Always include the protocol (http or https) and if not default for the
  # protocol, also the port number!
  origins:
    - http://localhost:3000/
    - http://localhost:3000

# UiTID related settings.
uitid:
  acc:
    consumer:
      key: 6d1137fab9c78ce0552dcea6d36b1c89
      secret: b60c459d6dec7a662fc11abf40a0434e
    base_url: https://acc.uitid.be/uitid/rest/
  prod:
    consumer:
      key: 6d1137fab9c78ce0552dcea6d36b1c89
      secret: b60c459d6dec7a662fc11abf40a0434e
    base_url: https://acc.uitid.be/uitid/rest/

# debug settings
debug: false

# set environment (acc or prod)
environment: acc
